-- MySQL Script generated by MySQL Workbench
-- Sun Mar 26 11:55:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `datanasc` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `avaliacao_media` INT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_veiculo`),
  INDEX `fk_veiculo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estacionamento` (
  `idestacionamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(65) NOT NULL,
  `n_vagas` INT NOT NULL,
  `vagas_disponiveis` VARCHAR(45) NOT NULL,
  `disponibilidade` INT NOT NULL,
  `avaliacao_ media` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idestacionamento`),
  INDEX `fk_estacionamento_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_estacionamento_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transacoes` (
  `idtransacoes` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `avaliacao_locatario` INT NULL,
  `avaliacao_locador` INT NULL,
  `status` VARCHAR(15) NOT NULL,
  `horario_inicio` VARCHAR(45) NOT NULL,
  `horario_saida` VARCHAR(45) NULL,
  `tempo` VARCHAR(45) NULL,
  `veiculo_id_veiculo` INT NOT NULL,
  `estacionamento_idestacionamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtransacoes`),
  INDEX `fk_transacoes_veiculo1_idx` (`veiculo_id_veiculo` ASC) VISIBLE,
  INDEX `fk_transacoes_estacionamento1_idx` (`estacionamento_idestacionamento` ASC) VISIBLE,
  CONSTRAINT `fk_transacoes_veiculo1`
    FOREIGN KEY (`veiculo_id_veiculo`)
    REFERENCES `mydb`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacoes_estacionamento1`
    FOREIGN KEY (`estacionamento_idestacionamento`)
    REFERENCES `mydb`.`estacionamento` (`idestacionamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
